@startuml
actor user
Participant backend
Database mysql
Queue kafka
Participant consumer

user -> backend: Search a product
activate backend
backend -> mysql: Get product
activate mysql
alt Get product successfully
    mysql --> backend: Return product data
    group Async Processing
        backend -> kafka: Produce user search activity
        activate kafka
        kafka -> consumer: Consume data
        deactivate kafka
        activate consumer
        consumer -> mysql: Update user search actitivity
        deactivate consumer
    end
    backend --> user: Return product info
else Get product failed
    mysql --> backend: Return error
    backend --> user: Return error
end
deactivate mysql
deactivate backend

@enduml